In [ ]:
import tensorflow as tf
import numpy
#!pip install tensorflow==2.3.0
#%tensorflow_version 1.x

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
tf.constant('caio')

<tf.Tensor: shape=(), dtype=string, numpy=b'caio'>

In [ ]:
# necessário decodificar para utf-8
tf.constant('cáio')

<tf.Tensor: shape=(), dtype=string, numpy=b'c\xc3\xa1io'>

In [ ]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.constant(3.2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.2>

In [ ]:
tf.constant([[1,2,3], [3,2,1]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 2, 1]], dtype=int32)>

In [ ]:
# atribuir o valor para um numero atribui para os restante (nesse caso sendo float)
tf.constant([[1.,2,3], [3,2,1]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [3., 2., 1.]], dtype=float32)>

In [ ]:
x = tf.constant([[1.,2,3], [3,2,1]])
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [3., 2., 1.]], dtype=float32)>

In [ ]:
x.numpy()

array([[1., 2., 3.],
       [3., 2., 1.]], dtype=float32)

In [ ]:
x = tf.Variable(2)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [ ]:
x = tf.Variable('letícia')

In [ ]:
x.numpy().decode('UTF-8')

'letícia'

In [ ]:
x = tf.Variable([[1,2], [1,2]])
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

In [ ]:
x = tf.Variable(2)

In [ ]:
## alterando o valor da variavel
x.assign(3)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=3>

In [ ]:

x.numpy()

3

In [ ]:
x = tf.Variable([[2,5], [10,9]])

In [ ]:
## alterando valor da matriz da linha 0, coluna 3
x[0,1].assign(3)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 2,  3],
       [10,  9]], dtype=int32)>

In [ ]:
x.numpy()

array([[ 2,  3],
       [10,  9]], dtype=int32)