In [1]:
import tensorflow as tf

In [2]:
A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[0,0],[1,0],[0,1]])

In [3]:
with tf.compat.v1.Session() as sess:
    A = tf.constant([[1, 2, 3],[4, 5, 6]])
    B = tf.constant([[0, 0],[1, 0],[0, 1]])
    x = tf.constant([0, 1, 0])
    # explandir um vetor. 1 é o eixo dimensional
    x = tf.expand_dims (x,1)
    resultado = tf.matmul(A, B)
    
    print(f' A: \n {sess.run(A)}')
    print(f' B: \n {sess.run(B)}')
    print(f' Resultado: \n {sess.run(resultado)} ')
    
    resultado2 = tf.matmul(A, x)
    
    print(f' Resultado 2: \n {sess.run(resultado2)} ')
    
    transposta = tf.transpose(A)
    print(f' A: \n {sess.run(transposta)}')

 A: 
 [[1 2 3]
 [4 5 6]]
 B: 
 [[0 0]
 [1 0]
 [0 1]]
 Resultado: 
 [[2 3]
 [5 6]] 
 Resultado 2: 
 [[2]
 [5]] 
 A: 
 [[1 4]
 [2 5]
 [3 6]]
